const dataBase = [
  { 
    id: 0,
    image: 'image/foto.jpg',
    title: 'Beautiful View',
    price: 458.83,
    type: 'shirt',
    discount: 2,
    amount: 0,
  },
  {
    id: 1,
    image: 'image/foto-1.jpg',
    title: 'Back To You',
    price: 1587.25,
    type: 'hats',
    discount: 3,
    amount: 0,
  },
  {
    id: 2,
    image: 'image/foto.jpg',
    title: 'Power Of Thought',
    price: 648.84,
    type: 'pants',
    discount: 8,
    amount: 0,
  },
  {
    id: 3,
    image: 'image/foto-1.jpg',
    title: 'The Depth Of The Sea',
    price: 549.58,
    type: 'shorts',
    discount: 5,
    amount: 0,
  },
  {
    id: 4,
    image: 'image/foto.jpg',
    title: 'The Sky Is Full',
    price: 348.54,
    type: 'shoes',
    discount: 4,
    amount: 0,
  },
  {
    id: 5,
    image: 'image/foto.jpg',
    title: 'The Master of Middle',
    price: 1657.84,
    type: 'pants',
    discount: 11,
    amount: 0,
  }
]